### This notebook will scrape market value and a small subset of player details for teams in La Liga. It pulls all data from www.transfermarkt.com
*** I kept the entire project in a single notebook for ease of reproduction while including formated notes. In an environment where this was going to be done on a scheduled basis I would create python files that I could run through the command line or use a scheduling tool to automate the runs ***

In [1]:
import requests, json, time, sqlite3
from bs4 import BeautifulSoup as bs
import pandas as pd
import numpy as np

# headers that will be used with url requests
headers = {'User-Agent': 
           'Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/47.0.2526.106 Safari/537.36'
          }

<ul>
    <li>requests is used to retrieve the HTML source code</li>
    <li>json converts the HTML source so it can be read by BeautifulSoup</li>
    <li>time is used to pause the code to avoid overloading server</li>
    <li>Beautifulsoup allows for easy searching of the HTML source data</li>
    <li>pandas is used to put the data into a dataframe so it can be stored as it is scraped then loaded to the database</li>
    <li>numpy is only used for np.nan in this project</li>
</ul>

In [2]:
urlTeamValue = r"https://www.transfermarkt.us/laliga/marktwerteverein/wettbewerb/ES1/stichtag"

# retrieve html data
json_team = requests.get(urlTeamValue, headers=headers)
team_soup = bs(json_team.text)

# accessing the html that has the desired data
table = team_soup.find("table", class_="items")
body = table.find("tbody")
rows = body.find_all("tr")

#data frame to hold team data
teams = pd.DataFrame(columns=['team','sourceId', 'marketValue','foreigners'])
for tr in rows:
    tds = tr.find_all("td")
    #team name
    team = tds[1].find("a")['title']
    
    # team source id will be used to create the url in the player scrape
    tid = tds[1].find("a")['href'].split("/")[4]
    
    # market value - formated to remove text
    marketValue = float(tds[5].text.replace("$","").replace("m", "").replace("Th.",""))
    
    # temp data frame with the row data that will be added to the main table
    temp = pd.DataFrame([[team, tid, marketValue]], columns = ["team", "sourceId", "marketValue"])
    teams = pd.concat((teams, temp))

# using team name as index
teams.set_index("team", inplace=True)

This retrieves the teams currently in La Liga and their market values. It stores them in a dataframe that will be joined with additional data below

In [3]:
urlForeigners = r"https://www.transfermarkt.us/laliga/legionaere/wettbewerb/ES1"

# retrieve html data
json_team = requests.get(urlForeigners, headers=headers)
forgn_soup = bs(json_team.text)
forgn_soup

# accessing the html that has the desired data
table = forgn_soup.find("table", class_="items")
body = table.find("tbody")
rows = body.find_all("tr")

for tr in rows:
    tds = tr.find_all("td")
    
    # team name
    team = tds[1].text
    
    # number of foreigners
    foreigners = int(tds[3].text)
    
    # adding foreigner count to the team data
    teams.loc[team, 'foreigners'] = foreigners

This retrieves the number of foreigners on each team retrieved in the prior code block and joins the data to the same dataframe.

## PLEASE NOTE THERE IS A 10 SECOND DELAY FOR EACH URL (20 URLs total) IN THE LOOP BELOW TO AVOID OVERLOADING THEIR SERVER AND TEMPORARY BLOCK

In [4]:
# requires string formatting to add the team name
urlPlayerValue = "https://www.transfermarkt.us/{team}/startseite/verein/{tid}/saison_id/2022"

# player dataframe that will receive data
players = pd.DataFrame(columns=['player','age','team','position', 'marketValue'])

# team names that will be used to build urls
team_names = dict(zip(teams.index, teams['sourceId']))

# looping through team names to visit their pages
for t, k in team_names.items():
    
    # retrieve html data
    url = urlPlayerValue.format(team=t.replace(" ", "-").lower(), tid=k)
    json_player = requests.get(url, headers=headers)
    player_soup = bs(json_player.text)

    # accessing the html that has the desired data
    table = player_soup.find("table", class_="items")
    body = table.find("tbody")
    rows = body.find_all("tr")
    
    for tr in rows:
        tds = tr.find_all("td")
        # skips html table rows that do not contain target data
        if len(tds) > 4:
            # position
            pos = tds[4].text

            # name
            name = tds[5].text

            # age
            age = int(tds[6].text.split("(")[1].replace(")", ""))

            # market value
            try:
                # raw market value
                marketValue = tds[8].text
                # checking if market value is in thousands
                inThousands = int(marketValue.find("Th"))
                if inThousands != -1:
                    #convert to MM if in Thousands
                    marketValue = float(marketValue.lower().replace("$", "").replace("th.", "")) / 1000
                else:
                    marketValue = float(marketValue.lower().replace("$", "").replace("m", ""))

            except:
                marketValue = np.nan

            # temp data frame with the row data that will be added to the main table
            temp = pd.DataFrame([[name, age, t, pos, marketValue]] , columns=['player','age', 'team', 'position', 'marketValue'])
            players = pd.concat([players, temp])
            
    # time out to avoid overloading website        
    time.sleep(10)

# grouping the  player positions into 4 groups
posMap = {'Goalkeeper':"gk", 'Centre-Back':"defender", 'Left-Back':"defender", 'Right-Back':"defender",
       'Defensive Midfield':"midfielder", 'Central Midfield':"midfielder", 'Left Winger':"forward",
       'Right Winger':"forward", 'Centre-Forward':"forward", 'Attacking Midfield':"midfielder",
       'Second Striker':"forward", 'Right Midfield':"midfielder", 'Left Midfield':"midfielder"}

players['position'] = players['position'].map(posMap)

This retrieves the player data from each team's URL. The solution to this prompt could be completed using Pandas functions on the player dataframe, shown below:

In [5]:
players.groupby(["team", "position"])['marketValue'].sum()

team                position
Athletic Bilbao     defender       65.89
                    forward        80.85
                    gk             33.00
                    midfielder     80.85
Atl√©tico de Madrid  defender      168.30
                                   ...
Valencia CF         midfielder     95.70
Villarreal CF       defender      134.75
                    forward       191.40
                    gk              8.47
                    midfielder     61.60
Name: marketValue, Length: 80, dtype: float64

### There are now 2 dataframes:
<ul>
    <li>TEAM - includes team name, website team ID, market value, and number of foreigners</li>
    <li>PLAYER - includes player name, age, team name, position, and market value</li>
</ul>

The next section will create an in-memory database, 2 tables, and populate the tables with the dataframes

# SQL DB

In [21]:
# queries to create db tables
queriesCreateTables = [
    """CREATE TABLE IF NOT EXISTS team (team TEXT PK, sourceId INTEGER, marketValue DECIMAL, foreigners INTEGER)""",
    """CREATE TABLE IF NOT EXISTS player (player TEXT PK, age INTEGER, team TEXT, position TEXT, marketValue DECIMAL)"""
]

# executing queries to create tables and populate them
conn = sqlite3.connect(":memory:")
c = conn.cursor()

# create tables
for i in queriesCreateTables:
    c.execute(i)

# populate tables
teams.to_sql('team', con=conn, if_exists='append', index=True)
players.to_sql('player', con=conn, if_exists='append', index=False)

# >>> SOLUTION QUERY <<<

In [16]:
# answer to the project prompt
# SELECT team, position, ROUND(SUM(marketValue),2) FROM player GROUP BY team, position;
c.execute("SELECT team, position, ROUND(SUM(marketValue),2) FROM player GROUP BY team, position;")
teamPosValue = c.fetchall()
teamPosValue

[('Athletic Bilbao', 'defender', 65.89),
 ('Athletic Bilbao', 'forward', 80.85),
 ('Athletic Bilbao', 'gk', 33.0),
 ('Athletic Bilbao', 'midfielder', 80.85),
 ('Atl√©tico de Madrid', 'defender', 168.3),
 ('Atl√©tico de Madrid', 'forward', 264.0),
 ('Atl√©tico de Madrid', 'gk', 47.85),
 ('Atl√©tico de Madrid', 'midfielder', 192.5),
 ('CA Osasuna', 'defender', 46.75),
 ('CA Osasuna', 'forward', 49.5),
 ('CA Osasuna', 'gk', 12.21),
 ('CA Osasuna', 'midfielder', 27.94),
 ('Celta de Vigo', 'defender', 44.0),
 ('Celta de Vigo', 'forward', 37.95),
 ('Celta de Vigo', 'gk', 5.72),
 ('Celta de Vigo', 'midfielder', 53.9),
 ('C√°diz CF', 'defender', 21.34),
 ('C√°diz CF', 'forward', 23.1),
 ('C√°diz CF', 'gk', 7.48),
 ('C√°diz CF', 'midfielder', 19.58),
 ('Elche CF', 'defender', 21.23),
 ('Elche CF', 'forward', 38.5),
 ('Elche CF', 'gk', 4.18),
 ('Elche CF', 'midfielder', 15.51),
 ('FC Barcelona', 'defender', 254.1),
 ('FC Barcelona', 'forward', 297.0),
 ('FC Barcelona', 'gk', 39.27),
 ('FC Barcelona', 'midfielder', 304.7),
 ('Getafe CF', 'defender', 44.88),
 ('Getafe CF', 'forward', 55.0),
 ('Getafe CF', 'gk', 9.9),
 ('Getafe CF', 'midfielder', 48.95),
 ('Girona FC', 'defender', 32.23),
 ('Girona FC', 'forward', 27.28),
 ('Girona FC', 'gk', 2.86),
 ('Girona FC', 'midfielder', 38.39),
 ('RCD Espanyol Barcelona', 'defender', 25.63),
 ('RCD Espanyol Barcelona', 'forward', 34.65),
 ('RCD Espanyol Barcelona', 'gk', 10.34),
 ('RCD Espanyol Barcelona', 'midfielder', 30.8),
 ('RCD Mallorca', 'defender', 20.68),
 ('RCD Mallorca', 'forward', 23.87),
 ('RCD Mallorca', 'gk', 12.43),
 ('RCD Mallorca', 'midfielder', 21.78),
 ('Rayo Vallecano', 'defender', 23.32),
 ('Rayo Vallecano', 'forward', 36.3),
 ('Rayo Vallecano', 'gk', 5.61),
 ('Rayo Vallecano', 'midfielder', 25.52),
 ('Real Betis Balompi√©', 'defender', 69.3),
 ('Real Betis Balompi√©', 'forward', 70.95),
 ('Real Betis Balompi√©', 'gk', 19.8),
 ('Real Betis Balompi√©', 'midfielder', 125.95),
 ('Real Madrid', 'defender', 256.3),
 ('Real Madrid', 'forward', 311.3),
 ('Real Madrid', 'gk', 68.75),
 ('Real Madrid', 'midfielder', 284.9),
 ('Real Sociedad', 'defender', 100.65),
 ('Real Sociedad', 'forward', 145.75),
 ('Real Sociedad', 'gk', 24.53),
 ('Real Sociedad', 'midfielder', 137.5),
 ('Real Valladolid CF', 'defender', 17.55),
 ('Real Valladolid CF', 'forward', 33.0),
 ('Real Valladolid CF', 'gk', 5.17),
 ('Real Valladolid CF', 'midfielder', 15.95),
 ('Sevilla FC', 'defender', 94.6),
 ('Sevilla FC', 'forward', 123.2),
 ('Sevilla FC', 'gk', 25.3),
 ('Sevilla FC', 'midfielder', 61.05),
 ('UD Almer√≠a', 'defender', 33.66),
 ('UD Almer√≠a', 'forward', 36.52),
 ('UD Almer√≠a', 'gk', 4.62),
 ('UD Almer√≠a', 'midfielder', 20.9),
 ('Valencia CF', 'defender', 83.05),
 ('Valencia CF', 'forward', 57.2),
 ('Valencia CF', 'gk', 24.97),
 ('Valencia CF', 'midfielder', 95.7),
 ('Villarreal CF', 'defender', 134.75),
 ('Villarreal CF', 'forward', 191.4),
 ('Villarreal CF', 'gk', 8.47),
 ('Villarreal CF', 'midfielder', 61.6)]

In [17]:
# The query could also be done directly into a dataframe for analysis
df = pd.read_sql("SELECT team, position, ROUND(SUM(marketValue),2) marketValue FROM player GROUP BY team, position;", con=conn)
conn.close()
df

                  team    position  marketValue
0      Athletic Bilbao    defender        65.89
1      Athletic Bilbao     forward        80.85
2      Athletic Bilbao          gk        33.00
3      Athletic Bilbao  midfielder        80.85
4   Atl√©tico de Madrid    defender       168.30
..                 ...         ...          ...
75         Valencia CF  midfielder        95.70
76       Villarreal CF    defender       134.75
77       Villarreal CF     forward       191.40
78       Villarreal CF          gk         8.47
79       Villarreal CF  midfielder        61.60

[80 rows x 3 columns]

## Thank you for reviewing my work, I look forward to talking with the team

In [ ]:
# saving the tables to csvs 
##### The names are not processed for non-standard characters to the USA alphabet. 
##### My Python and SQL solution does not require it so I did not include it in the project
##### The CSV files are only included for easier review of the application since the database would normally the storage tool.
players.to_csv("data/players.csv")
teams.to_csv("data/teams.csv")